### ISSUE TITLE
Any plans to update compatibility with PHP 8.1?

### ISSUE THREAD

**Issue by TheMY3** [TeleSign/php_telesign#19]
After upgrade to PHP 8.1 got error:

> PHP Deprecated http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated 
    [internal] http_build_query
    /vendor/telesign/telesign/src/rest/RestClient.php:210 telesign\sdk\rest\RestClient::execute
    /vendor/telesign/telesign/src/rest/RestClient.php:154 telesign\sdk\rest\RestClient::post
    /vendor/telesign/telesign/src/score/ScoreClient.php:22 telesign\sdk\score\ScoreClient::score

**Comment by sailingdeveloper** [comment]
Possible fix here: https://github.com/TeleSign/php_telesign/pull/20

**Comment by adohertyTS** [comment]
hi all! Telesign product manager here. We've updated this SDK to be compatible with PHP 8.1 in the latest version, addressing this issue. Please let me know if you run into any further difficulties. :D
